version: '2'
services:
  db_s:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    # ports:
    #   - 3306:3306
    volumes:
      - ./:/docker-entrypoint-initdb.d
